### ISSUE TITLE
Rectangle resize does not fit edges properly

### ISSUE THREAD

**Issue by chrjs** [summerstyle/summer#16]
When resizing a rectagle area, if the mouse moves fast outside the image boundaries, the rectangle area is resized up to last mousemove event before exiting the boundaries, instead of moving up to the edge coordinates.

**Comment by summerstyle** [comment]
Yes, but how it made:
mousemove event listens for the container of an image, not for all document,
this event fires not for every pixel,
so we have this problem for fast mouse moving.

The solution for this problem is attaching mousemove event for all document,
but this is more difficult than existing solution, and the problem is not critical(
